# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QSystemTrayIcon, QMenu
from PyQt5.QtGui import QIcon



class Janela(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 768)
        MainWindow.setMinimumSize(QtCore.QSize(1366, 768))
        MainWindow.setMaximumSize(QtCore.QSize(1366, 768))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon_close/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1366, 768))
        self.frame.setStyleSheet("background-color: rgb(235, 120, 59);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_erro = QtWidgets.QFrame(self.frame)
        self.frame_erro.setGeometry(QtCore.QRect(473, 3, 400, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.frame_erro.setFont(font)
        self.frame_erro.setStyleSheet("background-color: rgb(255, 32, 32);\n"
"border-radius: 8px;")





        self.frame_erro.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_erro.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_erro.setObjectName("frame_erro")
        self.label_error = QtWidgets.QLabel(self.frame_erro)
        self.label_error.setGeometry(QtCore.QRect(1, 1, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)

        self.label_error.setFont(font)
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.Pushbutton_close_erro = QtWidgets.QPushButton(self.frame_erro)
        self.Pushbutton_close_erro.setGeometry(QtCore.QRect(370, 8, 20, 20))
        self.Pushbutton_close_erro.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Pushbutton_close_erro.setStyleSheet("QPushButton {\n"
"    background-image: url(:/icon_close/cil-x.png);\n"
"    background-position: center;\n"
"    background-color: rgb(59, 59, 59);\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 7, 7);\n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 7, 7);\n"
"}")
        self.Pushbutton_close_erro.setText("")
        self.Pushbutton_close_erro.setObjectName("Pushbutton_close_erro")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(25, 35, 140, 100))
        self.frame_3.setStyleSheet("QFrame {\n"
"    border: 2px solid rgb(255,255,255);\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QLabel {\n"
"    border: 0px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 121, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 140, 100))
        self.frame_4.setStyleSheet("QFrame {\n"
"    border: 2px solid rgb(255,255,255);\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QLabel {\n"
"    border: 0px;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_numero_pedido = QtWidgets.QLabel(self.frame_4)
        self.label_numero_pedido.setGeometry(QtCore.QRect(10, 10, 121, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label_numero_pedido.setFont(font)
        self.label_numero_pedido.setAlignment(QtCore.Qt.AlignCenter)
        self.label_numero_pedido.setObjectName("label_numero_pedido")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(47, 4, 101, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.line_edit_nome_cliente = QtWidgets.QLineEdit(self.frame)
        self.line_edit_nome_cliente.setGeometry(QtCore.QRect(25, 170, 381, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.line_edit_nome_cliente.setFont(font)
        self.line_edit_nome_cliente.setStyleSheet("QLineEdit {\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255,255,255);\n"
"    padding: 4px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgb(153,15,29);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 3px solid rgb(153,15,29);\n"
"}")
        self.line_edit_nome_cliente.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.line_edit_nome_cliente.setClearButtonEnabled(False)
        self.line_edit_nome_cliente.setObjectName("line_edit_nome_cliente")
        self.line_edit_telefone_cliente = QtWidgets.QLineEdit(self.frame)
        self.line_edit_telefone_cliente.setGeometry(QtCore.QRect(420, 170, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.line_edit_telefone_cliente.setFont(font)
        self.line_edit_telefone_cliente.setStyleSheet("QLineEdit {\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255,255,255);\n"
"    padding: 4px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgb(153,15,29);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 3px solid rgb(153,15,29);\n"
"}")
        self.line_edit_telefone_cliente.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.line_edit_telefone_cliente.setClearButtonEnabled(False)
        self.line_edit_telefone_cliente.setObjectName("line_edit_telefone_cliente")
        self.lineEdit_ponto_referencia = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_ponto_referencia.setGeometry(QtCore.QRect(25, 350, 605, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lineEdit_ponto_referencia.setFont(font)
        self.lineEdit_ponto_referencia.setStyleSheet("QLineEdit {\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255,255,255);\n"
"    padding: 4px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgb(153,15,29);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 3px solid rgb(153,15,29);\n"
"}")
        self.lineEdit_ponto_referencia.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_ponto_referencia.setClearButtonEnabled(False)
        self.lineEdit_ponto_referencia.setObjectName("lineEdit_ponto_referencia")
        self.line_edit_endereco_cliente = QtWidgets.QLineEdit(self.frame)
        self.line_edit_endereco_cliente.setGeometry(QtCore.QRect(185, 260, 345, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.line_edit_endereco_cliente.setFont(font)
        self.line_edit_endereco_cliente.setStyleSheet("QLineEdit {\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255,255,255);\n"
"    padding: 4px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgb(153,15,29);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 3px solid rgb(153,15,29);\n"
"}")

        self.line_edit_endereco_cliente.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.line_edit_endereco_cliente.setClearButtonEnabled(False)
        self.line_edit_endereco_cliente.setObjectName("line_edit_endereco_cliente")
        self.comboBox_local_entrega = QtWidgets.QComboBox(self.frame)
        self.comboBox_local_entrega.setGeometry(QtCore.QRect(25, 260, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.comboBox_local_entrega.setFont(font)
        self.comboBox_local_entrega.setStyleSheet("QComboBox {\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255,255,255);\n"
"font-size: 17px;\n"
"}\n"
"QComboBox:pressed {\n"
"    border-radius: 8px;\n"
"    color: rgb(255,255,255);\n"
"}")
        self.comboBox_local_entrega.setObjectName("comboBox_local_entrega")
        self.comboBox_local_entrega.addItem("")
        self.comboBox_local_entrega.addItem("")
        self.comboBox_local_entrega.addItem("")
        self.comboBox_local_entrega.addItem("")
        self.comboBox_local_entrega.addItem("")
        self.lineEdit_numero_da_casa = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_numero_da_casa.setGeometry(QtCore.QRect(540, 260, 90, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.lineEdit_numero_da_casa.setFont(font)
        self.lineEdit_numero_da_casa.setStyleSheet("QLineEdit {\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255,255,255);\n"
"    padding: 4px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgb(153,15,29);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 3px solid rgb(153,15,29);\n"
"}")
        self.lineEdit_numero_da_casa.setMaxLength(5)
        self.lineEdit_numero_da_casa.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_numero_da_casa.setClearButtonEnabled(False)
        self.lineEdit_numero_da_casa.setObjectName("lineEdit_numero_da_casa")
        self.textEdit_observacoes = QtWidgets.QTextEdit(self.frame)
        self.textEdit_observacoes.setGeometry(QtCore.QRect(25, 600, 605, 150))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.textEdit_observacoes.setFont(font)
        self.textEdit_observacoes.setStyleSheet("QTextEdit {\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255,255,255);\n"
"    padding: 3px;\n"
"}\n"
"QTextEdit:focus {\n"
"border: 3px solid rgb(153,15,29);\n"
"}\n"
"QTextEdit:hover {\n"
"    border: 2px solid rgb(153,15,29);\n"
"}")
        self.textEdit_observacoes.setObjectName("textEdit_observacoes")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(35, 570, 131, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(30, 320, 201, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(30, 230, 101, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(190, 230, 101, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(30, 140, 141, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(425, 140, 101, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(545, 230, 101, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_hora_pedido = QtWidgets.QLabel(self.frame)
        self.label_hora_pedido.setGeometry(QtCore.QRect(190, 65, 120, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_hora_pedido.setFont(font)
        self.label_hora_pedido.setStyleSheet("QLabel{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"}")
        self.label_hora_pedido.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hora_pedido.setObjectName("label_hora_pedido")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(195, 35, 141, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_data_pedido = QtWidgets.QLabel(self.frame)
        self.label_data_pedido.setGeometry(QtCore.QRect(330, 85, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_data_pedido.setFont(font)
        self.label_data_pedido.setStyleSheet("QLabel{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"}")
        self.label_data_pedido.setAlignment(QtCore.Qt.AlignCenter)
        self.label_data_pedido.setObjectName("label_data_pedido")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(335, 55, 141, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.pushButton_novo_pedido = QtWidgets.QPushButton(self.frame)
        self.pushButton_novo_pedido.setGeometry(QtCore.QRect(520, 45, 111, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_novo_pedido.setFont(font)
        self.pushButton_novo_pedido.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_novo_pedido.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_novo_pedido.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(61, 196, 55,);\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    text-align: center;\n"
"    color: rgb(255,255,255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(70, 221, 55);\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(9, 165, 9);\n"
"}")
        self.pushButton_novo_pedido.setCheckable(False)
        self.pushButton_novo_pedido.setAutoExclusive(False)
        self.pushButton_novo_pedido.setFlat(False)
        self.pushButton_novo_pedido.setObjectName("pushButton_novo_pedido")
        self.comboBox_tamanho_pizza = QtWidgets.QComboBox(self.frame)
        self.comboBox_tamanho_pizza.setGeometry(QtCore.QRect(680, 100, 101, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.comboBox_tamanho_pizza.setFont(font)
        self.comboBox_tamanho_pizza.setStyleSheet("QComboBox {\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255,255,255);\n"
"font-size: 18px;\n"
"font-weight: bold\n"
"}\n"
"QComboBox:pressed {\n"
"    border-radius: 8px;\n"
"    color: rgb(255,255,255);\n"
"}")
        self.comboBox_tamanho_pizza.setObjectName("comboBox_tamanho_pizza")
        self.comboBox_tamanho_pizza.addItem("")
        self.comboBox_tamanho_pizza.addItem("")
        self.comboBox_tamanho_pizza.addItem("")
        self.comboBox_tamanho_pizza.addItem("")
        self.comboBox_1_sabor = QtWidgets.QComboBox(self.frame)
        self.comboBox_1_sabor.setGeometry(QtCore.QRect(785, 100, 150, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.comboBox_1_sabor.setFont(font)
        self.comboBox_1_sabor.setStyleSheet("background-color: white;\n"
"border-radius: 8px;\n"
"font-size: 13px;")
        self.comboBox_1_sabor.setObjectName("comboBox_1_sabor")
        self.comboBox_1_sabor.addItem("")
        self.comboBox_2_sabor = QtWidgets.QComboBox(self.frame)
        self.comboBox_2_sabor.setGeometry(QtCore.QRect(940, 100, 150, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.comboBox_2_sabor.setFont(font)
        self.comboBox_2_sabor.setStyleSheet("QComboBox {\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255,255,255);\n"
"    font-size: 13px;\n"
"}\n"
"QComboBox:pressed {\n"
"    border-radius: 8px;\n"
"    color: rgb(255,255,255);\n"
"}")

        self.comboBox_2_sabor.setObjectName("comboBox_2_sabor")
        self.comboBox_2_sabor.addItem("")
        self.comboBox_3_sabor = QtWidgets.QComboBox(self.frame)
        self.comboBox_3_sabor.setGeometry(QtCore.QRect(1095, 100, 150, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.comboBox_3_sabor.setFont(font)
        self.comboBox_3_sabor.setStyleSheet("QComboBox {\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255,255,255);\n"
"font-size: 13px;\n"
"}\n"
"QComboBox:pressed {\n"
"    border-radius: 8px;\n"
"    color: rgb(255,255,255);\n"
"}")
        self.comboBox_3_sabor.setObjectName("comboBox_3_sabor")
        self.comboBox_3_sabor.addItem("")
        self.comboBox_borda = QtWidgets.QComboBox(self.frame)
        self.comboBox_borda.setGeometry(QtCore.QRect(1250, 100, 111, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.comboBox_borda.setFont(font)
        self.comboBox_borda.setStyleSheet("QComboBox {\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QComboBox:pressed {\n"
"    border-radius: 8px;\n"
"    color: rgb(255,255,255);\n"
"}")
        self.comboBox_borda.setObjectName("comboBox_borda")
        self.comboBox_borda.addItem("")
        self.comboBox_borda.addItem("")
        self.comboBox_borda.addItem("")
        self.comboBox_borda.addItem("")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(682, 70, 101, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(790, 70, 101, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(945, 70, 101, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(1100, 70, 101, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setGeometry(QtCore.QRect(1255, 70, 101, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.list_view_pizzas = QtWidgets.QListWidget(self.frame)
        self.list_view_pizzas.setGeometry(QtCore.QRect(680, 190, 565, 192))
        self.list_view_pizzas.setStyleSheet("QListView{\n"
"    background-color: rgb(255,255,255);\n"
"    border-radius: 8px;\n"
"    padding: 3px;\n"
"font-size: 20px;"
"}")
        self.list_view_pizzas.setObjectName("list_view_pizzas")
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(680, 163, 565, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("QLabel{\n"
"    background-color: rgb(220,78,33);\n"
"    color: rgb(255,255,255);\n"
"    border-radius: 6px;\n"
"}")
        self.label_20.setObjectName("label_20")
        self.listView_refrigerantes_lista_de_itens = QtWidgets.QListWidget(self.frame)
        self.listView_refrigerantes_lista_de_itens.setGeometry(QtCore.QRect(680, 490, 565, 150))
        self.listView_refrigerantes_lista_de_itens.setStyleSheet("QListView{\n"
"    background-color: rgb(255,255,255);\n"
"    border-radius: 8px;\n"
"    padding: 3px;\n"
"font-size: 18px;\n"
"}")
        self.listView_refrigerantes_lista_de_itens.setObjectName("listView_refrigerantes_lista_de_itens")
        self.comboBox_refrigerante_opcao = QtWidgets.QComboBox(self.frame)
        self.comboBox_refrigerante_opcao.setGeometry(QtCore.QRect(680, 420, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.comboBox_refrigerante_opcao.setFont(font)
        self.comboBox_refrigerante_opcao.setStyleSheet("QComboBox {\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QComboBox:pressed {\n"
"    border-radius: 8px;\n"
"    color: rgb(255,255,255);\n"
"}")
        self.comboBox_refrigerante_opcao.setObjectName("comboBox_refrigerante_opcao")
        self.comboBox_refrigerante_opcao.addItem("")
        self.comboBox_refrigerante_opcao.addItem("")
        self.comboBox_refrigerante_opcao.addItem("")
        self.comboBox_refrigerante_opcao.addItem("")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(685, 395, 141, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.lineEdit_refrigerante_quantidade = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_refrigerante_quantidade.setGeometry(QtCore.QRect(915, 420, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_refrigerante_quantidade.setFont(font)
        self.lineEdit_refrigerante_quantidade.setStyleSheet("QLineEdit {\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgb(153,15,29);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(153,15,29);\n"
"}")
        self.lineEdit_refrigerante_quantidade.setMaxLength(1)
        self.lineEdit_refrigerante_quantidade.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_refrigerante_quantidade.setClearButtonEnabled(False)
        self.lineEdit_refrigerante_quantidade.setObjectName("lineEdit_refrigerante_quantidade")
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setGeometry(QtCore.QRect(920, 395, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame)
        self.label_23.setGeometry(QtCore.QRect(680, 463, 565, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("QLabel{\n"
"    background-color: rgb(220,78,33);\n"
"    color: rgb(255,255,255);\n"
"    border-radius: 6px;\n"
"}")
        self.label_23.setObjectName("label_23")
        self.pushButton_pizzas_novo_item = QtWidgets.QPushButton(self.frame)
        self.pushButton_pizzas_novo_item.setGeometry(QtCore.QRect(1255, 163, 100, 65))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_pizzas_novo_item.setFont(font)
        self.pushButton_pizzas_novo_item.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_pizzas_novo_item.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_pizzas_novo_item.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(244, 154, 15);\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    text-align: center;\n"
"    color: rgb(255,255,255);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgb(218, 211, 8);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(189, 152, 2)\n"
"}")
        self.pushButton_pizzas_novo_item.setCheckable(False)
        self.pushButton_pizzas_novo_item.setAutoExclusive(False)
        self.pushButton_pizzas_novo_item.setFlat(False)
        self.pushButton_pizzas_novo_item.setObjectName("pushButton_pizzas_novo_item")
        self.pushButton_pizzas_deletar_item = QtWidgets.QPushButton(self.frame)
        self.pushButton_pizzas_deletar_item.setGeometry(QtCore.QRect(1255, 238, 100, 65))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_pizzas_deletar_item.setFont(font)
        self.pushButton_pizzas_deletar_item.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_pizzas_deletar_item.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_pizzas_deletar_item.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(212, 23, 25);\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    text-align: center;\n"
"    color: rgb(255,255,255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 0, 4);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(162, 12, 15)\n"
"}")
        self.pushButton_pizzas_deletar_item.setCheckable(False)
        self.pushButton_pizzas_deletar_item.setAutoExclusive(False)
        self.pushButton_pizzas_deletar_item.setFlat(False)
        self.pushButton_pizzas_deletar_item.setObjectName("pushButton_pizzas_deletar_item")
        self.pushButton_pizzas_add_na_lista = QtWidgets.QPushButton(self.frame)
        self.pushButton_pizzas_add_na_lista.setGeometry(QtCore.QRect(1255, 313, 100, 65))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_pizzas_add_na_lista.setFont(font)
        self.pushButton_pizzas_add_na_lista.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_pizzas_add_na_lista.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_pizzas_add_na_lista.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(61, 196, 55,);\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    text-align: center;\n"
"    color: rgb(255,255,255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(70, 221, 55);\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(9, 165, 9);\n"
"}")
        self.pushButton_pizzas_add_na_lista.setCheckable(False)
        self.pushButton_pizzas_add_na_lista.setAutoExclusive(False)
        self.pushButton_pizzas_add_na_lista.setFlat(False)
        self.pushButton_pizzas_add_na_lista.setObjectName("pushButton_pizzas_add_na_lista")
        self.pushButton_refri_deletar_item = QtWidgets.QPushButton(self.frame)
        self.pushButton_refri_deletar_item.setGeometry(QtCore.QRect(1260, 525, 100, 55))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_refri_deletar_item.setFont(font)
        self.pushButton_refri_deletar_item.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_refri_deletar_item.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_refri_deletar_item.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(212, 23, 25);\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    text-align: center;\n"
"    color: rgb(255,255,255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 0, 4);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(162, 12, 15)\n"
"}")
        self.pushButton_refri_deletar_item.setCheckable(False)
        self.pushButton_refri_deletar_item.setAutoExclusive(False)
        self.pushButton_refri_deletar_item.setFlat(False)
        self.pushButton_refri_deletar_item.setObjectName("pushButton_refri_deletar_item")
        self.pushButton_refri_add_na_lista = QtWidgets.QPushButton(self.frame)
        self.pushButton_refri_add_na_lista.setGeometry(QtCore.QRect(1260, 590, 100, 55))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_refri_add_na_lista.setFont(font)
        self.pushButton_refri_add_na_lista.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_refri_add_na_lista.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_refri_add_na_lista.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(61, 196, 55,);\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    text-align: center;\n"
"    color: rgb(255,255,255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(70, 221, 55);\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(9, 165, 9);\n"
"}")
        self.pushButton_refri_add_na_lista.setCheckable(False)
        self.pushButton_refri_add_na_lista.setAutoExclusive(False)
        self.pushButton_refri_add_na_lista.setFlat(False)
        self.pushButton_refri_add_na_lista.setObjectName("pushButton_refri_add_na_lista")
        self.pushButton_refri_novo_item = QtWidgets.QPushButton(self.frame)
        self.pushButton_refri_novo_item.setGeometry(QtCore.QRect(1260, 460, 100, 55))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_refri_novo_item.setFont(font)
        self.pushButton_refri_novo_item.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_refri_novo_item.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_refri_novo_item.setStyleSheet("QPushButton {\n"
"    background-color: rgb(244, 154, 15);\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    text-align: center;\n"
"    color: rgb(255,255,255);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgb(218, 211, 8);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(189, 152, 2)\n"
"}")
        self.pushButton_refri_novo_item.setCheckable(False)
        self.pushButton_refri_novo_item.setAutoExclusive(False)
        self.pushButton_refri_novo_item.setFlat(False)
        self.pushButton_refri_novo_item.setObjectName("pushButton_refri_novo_item")
        self.pushButton_finalizar_pedido = QtWidgets.QPushButton(self.frame)
        self.pushButton_finalizar_pedido.setGeometry(QtCore.QRect(1260, 660, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_finalizar_pedido.setFont(font)
        self.pushButton_finalizar_pedido.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_finalizar_pedido.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_finalizar_pedido.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(212, 23, 25);\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    text-align: center;\n"
"    color: rgb(255,255,255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 0, 4);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(162, 12, 15)\n"
"}")
        self.pushButton_finalizar_pedido.setCheckable(False)
        self.pushButton_finalizar_pedido.setAutoExclusive(False)
        self.pushButton_finalizar_pedido.setFlat(False)
        self.pushButton_finalizar_pedido.setObjectName("pushButton_finalizar_pedido")
        self.comboBox_forma_pagamento = QtWidgets.QComboBox(self.frame)
        self.comboBox_forma_pagamento.setGeometry(QtCore.QRect(680, 700, 120, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.comboBox_forma_pagamento.setFont(font)
        self.comboBox_forma_pagamento.setStyleSheet("QComboBox {\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QComboBox:pressed {\n"
"    border-radius: 8px;\n"
"    color: rgb(255,255,255);\n"
"}")
        self.comboBox_forma_pagamento.setObjectName("comboBox_forma_pagamento")
        self.comboBox_forma_pagamento.addItem("")
        self.comboBox_forma_pagamento.addItem("")
        self.comboBox_forma_pagamento.addItem("")
        self.label_24 = QtWidgets.QLabel(self.frame)
        self.label_24.setGeometry(QtCore.QRect(680, 670, 181, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.lineEdit_desconto = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_desconto.setGeometry(QtCore.QRect(820, 700, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.lineEdit_desconto.setFont(font)
        self.lineEdit_desconto.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(255,255,255);\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255,255,255);\n"
"    padding: 4px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(153,15,29);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(153,15,29);\n"
"}")
        self.lineEdit_desconto.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_desconto.setClearButtonEnabled(False)
        self.lineEdit_desconto.setObjectName("lineEdit_desconto")
        self.label_25 = QtWidgets.QLabel(self.frame)
        self.label_25.setGeometry(QtCore.QRect(825, 670, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.lineEdit_troco = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_troco.setGeometry(QtCore.QRect(930, 700, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.lineEdit_troco.setFont(font)
        self.lineEdit_troco.setStyleSheet("QLineEdit {\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255,255,255);\n"
"    padding: 4px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(153,15,29);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(153,15,29);\n"
"}")
        self.lineEdit_troco.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_troco.setClearButtonEnabled(False)
        self.lineEdit_troco.setObjectName("lineEdit_troco")
        self.label_26 = QtWidgets.QLabel(self.frame)
        self.label_26.setGeometry(QtCore.QRect(930, 670, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(1080, 680, 140, 60))
        self.frame_5.setStyleSheet("QFrame {\n"
"    border: 2px solid rgb(255,255,255);\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_valor_total = QtWidgets.QLabel(self.frame_5)
        self.label_valor_total.setGeometry(QtCore.QRect(10, 10, 121, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_valor_total.setFont(font)
        self.label_valor_total.setAlignment(QtCore.Qt.AlignCenter)
        self.label_valor_total.setObjectName("label_valor_total")
        self.label_29 = QtWidgets.QLabel(self.frame)
        self.label_29.setGeometry(QtCore.QRect(1080, 650, 141, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)






    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mister Massas"))
        self.label_error.setText(_translate("MainWindow", "Mensagem de erro"))
        self.label_2.setText(_translate("MainWindow", "01"))
        self.label_numero_pedido.setText(_translate("MainWindow", "X"))
        self.label_3.setText(_translate("MainWindow", "Nº pedido"))
        self.line_edit_nome_cliente.setPlaceholderText(_translate("MainWindow", "Digite o nome "))
        self.line_edit_telefone_cliente.setPlaceholderText(_translate("MainWindow", "Digite o telefone"))
        self.lineEdit_ponto_referencia.setPlaceholderText(_translate("MainWindow", "Ponto de referência"))
        self.line_edit_endereco_cliente.setPlaceholderText(_translate("MainWindow", "Endereço "))
        self.comboBox_local_entrega.setItemText(0, _translate("MainWindow", "Buzios"))
        self.comboBox_local_entrega.setItemText(1, _translate("MainWindow", "Pirangi_do_sul"))
        self.comboBox_local_entrega.setItemText(2, _translate("MainWindow", "Pirangi_do_norte"))
        self.comboBox_local_entrega.setItemText(3, _translate("MainWindow", "Tabatinga_01"))
        self.comboBox_local_entrega.setItemText(4, _translate("MainWindow", "Tabatinga_02"))
        self.lineEdit_numero_da_casa.setPlaceholderText(_translate("MainWindow", "Nº"))
        self.textEdit_observacoes.setPlaceholderText(_translate("MainWindow", "Digite as observações"))
        self.label_4.setText(_translate("MainWindow", "Observações"))
        self.label_5.setText(_translate("MainWindow", "Ponto de referência"))
        self.label_6.setText(_translate("MainWindow", "Bairro"))
        self.label_7.setText(_translate("MainWindow", "Endereço"))
        self.label_8.setText(_translate("MainWindow", "Nome/Cliente"))
        self.label_9.setText(_translate("MainWindow", "Telefone"))
        self.label_10.setText(_translate("MainWindow", "Nº "))
        self.label_hora_pedido.setText(_translate("MainWindow", "00:00"))
        self.label_12.setText(_translate("MainWindow", "Hora/pedido"))
        self.label_data_pedido.setText(_translate("MainWindow", "00/00/0000"))
        self.label_14.setText(_translate("MainWindow", "Data"))
        self.pushButton_novo_pedido.setText(_translate("MainWindow", "Novo\n"
"Pedido"))
        self.comboBox_tamanho_pizza.setItemText(0, _translate("MainWindow", "Broto"))
        self.comboBox_tamanho_pizza.setItemText(1, _translate("MainWindow", "M"))
        self.comboBox_tamanho_pizza.setItemText(2, _translate("MainWindow", "G"))
        self.comboBox_tamanho_pizza.setItemText(3, _translate("MainWindow", "GG"))
        self.comboBox_1_sabor.setItemText(0, _translate("MainWindow", "Nenhum"))
        self.comboBox_2_sabor.setItemText(0, _translate("MainWindow", "Nenhum"))
        self.comboBox_3_sabor.setItemText(0, _translate("MainWindow", "Nenhum"))
        self.comboBox_borda.setItemText(0, _translate("MainWindow", "Sem_borda"))
        self.comboBox_borda.setItemText(1, _translate("MainWindow", "Chocolate"))
        self.comboBox_borda.setItemText(2, _translate("MainWindow", "Catupiry"))
        self.comboBox_borda.setItemText(3, _translate("MainWindow", "Cheddar"))
        self.label_15.setText(_translate("MainWindow", "Tamanho"))
        self.label_16.setText(_translate("MainWindow", "1º Sabor"))
        self.label_17.setText(_translate("MainWindow", "2º Sabor"))
        self.label_18.setText(_translate("MainWindow", "3º Sabor"))
        self.label_19.setText(_translate("MainWindow", "Borda"))
        self.label_20.setText(_translate("MainWindow", "  Tam       Detalhes do produto / Borda / Preço"))
        self.comboBox_refrigerante_opcao.setItemText(0, _translate("MainWindow", "Nenhum"))
        self.comboBox_refrigerante_opcao.setItemText(1, _translate("MainWindow", "Coca-Cola-1L"))
        self.comboBox_refrigerante_opcao.setItemText(2, _translate("MainWindow", "Coca-Cola-Zero"))
        self.comboBox_refrigerante_opcao.setItemText(3, _translate("MainWindow", "Guaraná-1L             "))
        self.label_21.setText(_translate("MainWindow", "Refrigerante"))
        self.lineEdit_refrigerante_quantidade.setPlaceholderText(_translate("MainWindow", "Nº"))
        self.label_22.setText(_translate("MainWindow", "Quantidade"))
        self.label_23.setText(_translate("MainWindow", "  Refrigerante                         Quantidade                              Preço"))
        self.pushButton_pizzas_novo_item.setText(_translate("MainWindow", "Novo\n"
" item"))
        self.pushButton_pizzas_deletar_item.setText(_translate("MainWindow", "Deletar\n"
"Item"))
        self.pushButton_pizzas_add_na_lista.setText(_translate("MainWindow", "Adicionar"))
        self.pushButton_refri_deletar_item.setText(_translate("MainWindow", "Deletar\n"
"Item"))
        self.pushButton_refri_add_na_lista.setText(_translate("MainWindow", "Adicionar"))
        self.pushButton_refri_novo_item.setText(_translate("MainWindow", "Novo \n"
" Item"))
        self.pushButton_finalizar_pedido.setText(_translate("MainWindow", "FINALIZAR\n"
"PEDIDO"))
        self.comboBox_forma_pagamento.setItemText(0, _translate("MainWindow", "PIX"))
        self.comboBox_forma_pagamento.setItemText(1, _translate("MainWindow", "DINHEIRO"))
        self.comboBox_forma_pagamento.setItemText(2, _translate("MainWindow", "CARTÃO"))
        self.label_24.setText(_translate("MainWindow", "Forma/pagamento"))
        self.lineEdit_desconto.setPlaceholderText(_translate("MainWindow", "R$"))
        self.label_25.setText(_translate("MainWindow", "Desconto"))
        self.lineEdit_troco.setPlaceholderText(_translate("MainWindow", "R$"))
        self.label_26.setText(_translate("MainWindow", "Troco"))
        self.label_valor_total.setText(_translate("MainWindow", "R$ 0.00"))
        self.label_29.setText(_translate("MainWindow", "Valor Total"))

        #sabor 1
        self.comboBox_1_sabor.addItem('Mussarela')
        self.comboBox_1_sabor.addItem('Marguerita')
        self.comboBox_1_sabor.addItem('Mista')
        self.comboBox_1_sabor.addItem('Frango')
        self.comboBox_1_sabor.addItem('Frango_C_Catupiry')
        self.comboBox_1_sabor.addItem('Frango_C_Bacon ')
        self.comboBox_1_sabor.addItem('Calabresa')
        self.comboBox_1_sabor.addItem('Calabresa_C_Cheddar')
        self.comboBox_1_sabor.addItem('Bacon')
        self.comboBox_1_sabor.addItem('Lombinho')
        self.comboBox_1_sabor.addItem('Portuguesa')
        self.comboBox_1_sabor.addItem('Brocólis')
        self.comboBox_1_sabor.addItem('Vegetariana')
        self.comboBox_1_sabor.addItem('Siciliana')
        self.comboBox_1_sabor.addItem('Atum')
        self.comboBox_1_sabor.addItem('Quatro_Queijos')
        self.comboBox_1_sabor.addItem('Cinco_Queijos')
        self.comboBox_1_sabor.addItem('Carne_De_Sol')
        self.comboBox_1_sabor.addItem('Calabresa_Especial')
        self.comboBox_1_sabor.addItem('Pepperoni')
        self.comboBox_1_sabor.addItem('Americana')
        self.comboBox_1_sabor.addItem('Carne_De_Sol_Esp.')
        self.comboBox_1_sabor.addItem('Sertaneja')
        self.comboBox_1_sabor.addItem('Camarão_C_Catupiry')
        self.comboBox_1_sabor.addItem('Camarão_à_Marguerita')
        self.comboBox_1_sabor.addItem('Chocolate')
        self.comboBox_1_sabor.addItem('Banana_C_Canela')
        self.comboBox_1_sabor.addItem('Banana_C_Chocolate')
        self.comboBox_1_sabor.addItem('Banana_Nevada')
        self.comboBox_1_sabor.addItem('Romeu_E_Julieta')


        #sabor 2
        self.comboBox_2_sabor.addItem('Mussarela')
        self.comboBox_2_sabor.addItem('Marguerita')
        self.comboBox_2_sabor.addItem('Mista')
        self.comboBox_2_sabor.addItem('Frango')
        self.comboBox_2_sabor.addItem('Frango_C_Catupiry')
        self.comboBox_2_sabor.addItem('Frango_C_Bacon ')
        self.comboBox_2_sabor.addItem('Calabresa')
        self.comboBox_2_sabor.addItem('Calabresa_C_Cheddar')
        self.comboBox_2_sabor.addItem('Bacon')
        self.comboBox_2_sabor.addItem('Lombinho')
        self.comboBox_2_sabor.addItem('Portuguesa')
        self.comboBox_2_sabor.addItem('Brocólis')
        self.comboBox_2_sabor.addItem('Vegetariana')
        self.comboBox_2_sabor.addItem('Siciliana')
        self.comboBox_2_sabor.addItem('Atum')
        self.comboBox_2_sabor.addItem('Quatro_Queijos')
        self.comboBox_2_sabor.addItem('Cinco_Queijos')
        self.comboBox_2_sabor.addItem('Carne_De_Sol')
        self.comboBox_2_sabor.addItem('Calabresa_Especial')
        self.comboBox_2_sabor.addItem('Pepperoni')
        self.comboBox_2_sabor.addItem('Americana')
        self.comboBox_2_sabor.addItem('Carne_De_Sol_Esp.')
        self.comboBox_2_sabor.addItem('Sertaneja')
        self.comboBox_2_sabor.addItem('Camarão_C_Catupiry')
        self.comboBox_2_sabor.addItem('Camarão_à_Marguerita')
        self.comboBox_2_sabor.addItem('Chocolate')
        self.comboBox_2_sabor.addItem('Banana_C_Canela')
        self.comboBox_2_sabor.addItem('Banana_C_Chocolate')
        self.comboBox_2_sabor.addItem('Banana_Nevada')
        self.comboBox_2_sabor.addItem('Romeu_E_Julieta')

        #sabor 3

        self.comboBox_3_sabor.addItem('Mussarela')
        self.comboBox_3_sabor.addItem('Marguerita')
        self.comboBox_3_sabor.addItem('Mista')
        self.comboBox_3_sabor.addItem('Frango')
        self.comboBox_3_sabor.addItem('Frango_C_Catupiry')
        self.comboBox_3_sabor.addItem('Frango_C_Bacon ')
        self.comboBox_3_sabor.addItem('Calabresa')
        self.comboBox_3_sabor.addItem('Calabresa_C_Cheddar')
        self.comboBox_3_sabor.addItem('Bacon')
        self.comboBox_3_sabor.addItem('Lombinho')
        self.comboBox_3_sabor.addItem('Portuguesa')
        self.comboBox_3_sabor.addItem('Brocólis')
        self.comboBox_3_sabor.addItem('Vegetariana')
        self.comboBox_3_sabor.addItem('Siciliana')
        self.comboBox_3_sabor.addItem('Atum')
        self.comboBox_3_sabor.addItem('Quatro_Queijos')
        self.comboBox_3_sabor.addItem('Cinco_Queijos')
        self.comboBox_3_sabor.addItem('Carne_De_Sol')
        self.comboBox_3_sabor.addItem('Calabresa_Especial')
        self.comboBox_3_sabor.addItem('Pepperoni')
        self.comboBox_3_sabor.addItem('Americana')
        self.comboBox_3_sabor.addItem('Carne_De_Sol_Esp.')
        self.comboBox_3_sabor.addItem('Sertaneja')
        self.comboBox_3_sabor.addItem('Camarão_C_Catupiry')
        self.comboBox_3_sabor.addItem('Camarão_à_Marguerita')
        self.comboBox_3_sabor.addItem('Chocolate')
        self.comboBox_3_sabor.addItem('Banana_C_Canela')
        self.comboBox_3_sabor.addItem('Banana_C_Chocolate')
        self.comboBox_3_sabor.addItem('Banana_Nevada')
        self.comboBox_3_sabor.addItem('Romeu_E_Julieta')


import grafico.media

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Janela()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
